### ISSUE TITLE
Issues about ICRA19_Ranging

### ISSUE THREAD

**Issue by cavayangtao** [TUC-ProAut/libRSF#13] opened 2023-04-28 08:31 UTC
Hi Tim,
many thanks for releasing this impressive work. The demo of ICRA19_GNSS runs smoothly, but I have some issues about the demo of ICRA19_Ranging.
When I use:
libRSF/build/applications/ICRA19_Ranging libRSF/datasets/Indoor UWB/Indoor_UWB_Input.txt Result_Indoor_UWB.txt error: stmm
It reports:
Error in ICRA19_Ranging.cpp | Line 257 | ParseErrorModel(): Wrong Error Model: error:
Then I use:
libRSF/build/applications/ICRA19_Ranging libRSF/datasets/Indoor UWB/Indoor_UWB_Input.txt Result_Indoor_UWB.txt stmm
It reports:
Error in DataSet.h | Line 174 | getElement(): Element doesn't exist at: 0 Type: 22 Number: 0
Error in Data.cpp | Line 98 | getStdDevDiagonal(): Data has no covariance element!

Regards,
Tao

**Comment by cavayangtao** [comment] 2023-04-28 08:49
I also change the folder name of "Indoor UWB" to "Indoor_UWB", and run:
libRSF/build/applications/ICRA19_Ranging libRSF/datasets/Indoor_UWB/Indoor_UWB_Input.txt Result_Indoor_UWB.txt error: stmm
It reports:
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stod
Aborted (core dumped)

**Comment by tipf** [comment] 2023-04-28 11:37
Hi Tao,
Thanks for raising this issue. 
I can reproduce the error and will try to find the reason for it.

I did not include the ranging application in the automated tests, so it could be broken by recent changes.

**Comment by tipf** [comment] 2023-04-28 13:52
Should be fixed by 0cfde758808a28f87872c0a0f03d9b8177708323.
I recently added an additional field to the range data definition that was missing from the old data set.

**Closed as completed by tipf** 2023-04-28 13:52 UTC
